name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: "42 15 * * *"
jobs:
  determine-latest-breaking-hhvm-version:
    runs-on: ubuntu-latest
    outputs:
      latest-breaking-hhvm-version: ${{steps.determine-latest-breaking-hhvm-version.outputs.latest-breaking-hhvm-version}}
    steps:
      - uses: actions/checkout@v3
      - id: determine-latest-breaking-hhvm-version
        run: |
          [[ \
            "$(<codegen-no-rebuild/latest_breaking_version.hack)" \
            =~ const\ string\ LATEST_BREAKING_HHVM_VERSION\ =\ \'([0-9]+\.[0-9]+)\. \
          ]] && \
          echo "::set-output name=latest-breaking-hhvm-version::${BASH_REMATCH[1]}"
  build:
    needs: determine-latest-breaking-hhvm-version
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        hhvm:
          - ${{needs.determine-latest-breaking-hhvm-version.outputs.latest-breaking-hhvm-version}}
          - latest
          - nightly
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          # We need bin/hhast-lint instead of vendor/bin/hhast-lint
          skip_lint: true
      - name: Lint
        run: bin/hhast-lint
      - name: Check for manually modified codegen
        run: vendor/bin/hh-codegen-verify-signatures codegen/
  update-schema:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: nightly
          skip_lint: true
          skip_tests: true
      - if: github.event_name == 'pull_request'
        run: bin/update-codegen
      - if: github.event_name == 'pull_request'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: Update schema
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v3
        with:
          submodules: true
          repository: facebook/hhvm
          path: ./.var/tmp/hhvm
      - if: github.event_name != 'pull_request'
        run: bin/update-schema --hhvm-path=./.var/tmp/hhvm
      - if: github.event_name != 'pull_request'
        id: pull-request-to-update-schema
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-schema/${{github.ref_name}}
          title: Update schema
          commit-message: Update schema
      - if: github.event_name != 'pull_request'
        run: git checkout -B "${{github.ref_name}}"
      - if: github.event_name != 'pull_request'
        run: bin/update-codegen --dont-update-ast --update-latest-breaking-version
      - if: github.event_name != 'pull_request'
        id: determine-latest-breaking-hhvm-version
        run: |
          [[ \
            "$(<codegen-no-rebuild/latest_breaking_version.hack)" \
            =~ const\ string\ LATEST_BREAKING_HHVM_VERSION\ =\ \'([0-9]+\.[0-9]+)\. \
          ]] && \
          echo "::set-output name=latest-breaking-hhvm-version::${BASH_REMATCH[1]}"
      - if: github.event_name != 'pull_request'
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            jq '.require.hhvm = "^${{steps.determine-latest-breaking-hhvm-version.outputs.latest-breaking-hhvm-version}}"' composer.json > composer.json.tmp && mv composer.json.tmp composer.json
      - if: github.event_name != 'pull_request'
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: HEAD
          filters: |
            any-changes: '**'
      - if: github.event_name != 'pull_request' && steps.filter.outputs.any-changes == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-latest-breaking-version/${{github.ref_name}}
          title: Update schema to a backward incompatible version
          commit-message: Update the latest breaking version
          body: |
            This PR assumes the latest schema is a breaking change.
            Feel free to close this PR and instead merge #${{steps.pull-request-to-update-schema.outputs.pull-request-number}}, if the schema is actually backward compatible with previous schema versions.
